#ifndef WORDS_EN
#define WORDS_EN


#include "definitions.hpp"


namespace fillw
{

	inline word_list_type word_list_en = 
	{
		{
			L"absolutely",
			L"accordingly",
			L"additionally",
			L"actual",
			L"actually",
			L"admittedly",
			L"afterwards",
			L"almost",
			L"already",
			L"also",
			L"although",
			L"altogether",
			L"amazing",
			L"another",
			L"anyway",
			L"apparently",
			L"approximately",
			L"badly",
			L"basically",
			L"begin",
			L"besides",
			L"briefly",
			L"but",
			L"certainly",
			L"clearly",
			L"coincidentally",
			L"commonly",
			L"completely",
			L"concerning",
			L"consequently",
			L"considering",
			L"conversely",
			L"could",
			L"definitely",
			L"despite",
			L"easily",
			L"effectively",
			L"entirely",
			L"equally",
			L"especially",
			L"essentially",
			L"eventually",
			L"exactly",
			L"extremely",
			L"fairly",
			L"finally",
			L"frankly",
			L"frequently",
			L"fully",
			L"furthermore",
			L"generally",
			L"good",
			L"hardly",
			L"heavily",
			L"hence",
			L"highly",
			L"hopefully",
			L"however",
			L"I",
			L"inasmuch",
			L"incidentally",
			L"indeed",
			L"initially",
			L"insofar",
			L"just",
			L"largely",
			L"lastly",
			L"like",
			L"likewise",
			L"literally",
			L"may",
			L"maybe",
			L"might",
			L"moreover",
			L"most",
			L"mostly",
			L"much",
			L"my",
			L"namely",
			L"naturally",
			L"necessarily",
			L"nevertheless",
			L"next",
			L"nice",
			L"nonetheless",
			L"notwithstanding",
			L"next",
			L"nicely",
			L"notably",
			L"obviously",
			L"ok",
			L"okay",
			L"only",
			L"otherwise",
			L"our",
			L"overall",
			L"particularly",
			L"perhaps",
			L"possibly",
			L"practically",
			L"previously",
			L"primarily",
			L"probably",
			L"precisely",
			L"quite",
			L"rather",
			L"real",
			L"really",
			L"recently",
			L"regarding",
			L"regardless",
			L"relatively",
			L"right",
			L"secondly",
			L"seriously",
			L"should",
			L"significantly",
			L"similarly",
			L"simply",
			L"since",
			L"slightly",
			L"so",
			L"somehow",
			L"specifically",
			L"start",
			L"still",
			L"strongly",
			L"stuff",
			L"subsequently",
			L"summarizing",
			L"surely",
			L"therefore",
			L"thing",
			L"things",
			L"thirdly",
			L"thus",
			L"too",
			L"totally",
			L"traditionally",
			L"truly",
			L"try",
			L"typically",
			L"ultimately",
			L"undoubtedly",
			L"unless",
			L"usually",
			L"very",
			L"virtually",
			L"we",
			L"well",
			L"whatever",
			L"whenever",
			L"whereas",
			L"wherever",
			L"while",
			L"whoever",
			L"widely",
			L"would",
			L"yet"
		},

		{
			L"a little",
			L"above all",
			L"according to",
			L"adjacent to",
			L"after all",
			L"and yet",
			L"are shown",
			L"are presented",
			L"as being",
			L"as discussed",
			L"as exemplified",
			L"as explained",
			L"as for",
			L"as illustrated",
			L"as mentioned",
			L"as of",
			L"as said",
			L"as shown",
			L"as stated",
			L"as yet",
			L"at least",
			L"at length",
			L"be said",
			L"be seen",
			L"be shown",
			L"because of",
			L"but also",
			L"can be",
			L"considering this",
			L"could possibly",
			L"due to",
			L"either way",
			L"even if",
			L"even more",
			L"even so",
			L"even though",
			L"following the",
			L"following this",
			L"for example",
			L"for instance",
			L"given that",
			L"granted that",
			L"granting that",
			L"if so",
			L"in addition",
			L"in brief ",
			L"in case",
			L"in conclusion",
			L"in contrast",
			L"in fact",
			L"in general",
			L"in particular",
			L"is presented",
			L"in short",
			L"in summary",
			L"is described",
			L"is known",
			L"is possible",
			L"is shown",
			L"is used",
			L"inasmuch as",
			L"kind of",
			L"looking at",
			L"more importantly",
			L"more specifically",
			L"most importantly",
			L"neighboring on",
			L"next chapter",
			L"next page",
			L"not only",
			L"of course",
			L"once again",
			L"only if",
			L"on one hand",
			L"opposite to",
			L"outside of",
			L"owing to",
			L"prior to",
			L"provided that",
			L"show that",
			L"shows that",
			L"sort of",
			L"such as",
			L"taken together",
			L"that is",
			L"that means",
			L"the goal",
			L"the purpose",
			L"this approach",
			L"this chapter",
			L"this is",
			L"this means",
			L"this method",
			L"this project",
			L"this research",
			L"this section",
			L"this work",
			L"thus to",
			L"to clarify",
			L"to conclude",
			L"to demonstrate",
			L"to explain",
			L"to illustrate",
			L"to repeat",
			L"to resume",
			L"used to",
			L"was shown",
			L"was used",
			L"whatever happens",
			L"will be",
			L"with reference",
			L"with this",
			L"without doubt",
			L"would be",
			L"you know",
			L"you see"
		},

		{
			L"all the same",
			L"as a consequence",
			L"as a result",
			L"as an illustration",
			L"as long as",
			L"as to whether",
			L"as was mentioned",
			L"as was shown",
			L"as was said",
			L"as well as",
			L"as stated before",
			L"at all times",
			L"at any rate",
			L"by the way",
			L"each and every",
			L"first of all ",
			L"for the purpose of",
			L"for the purposes of",
			L"for this reason",
			L"for these reasons",
			L"given these points",
			L"here’s the thing",
			L"here's the deal",
			L"I might add",
			L"in a nutshell",
			L"in a word ",
			L"in addition to",
			L"in all cases",
			L"in any case",
			L"in any event",
			L"in both cases",
			L"in like manner",
			L"in my opinion",
			L"in our opinion",
			L"in order that",
			L"in order to",
			L"in other words",
			L"in other terms",
			L"in similar fashion",
			L"in spite of",
			L"in terms of",
			L"in that case",
			L"in the assumption",
			L"in the case",
			L"in the event",
			L"in the end",
			L"in the hope",
			L"in the meantime",
			L"in the process",
			L"in this case",
			L"in this thesis",
			L"in this work",
			L"in view of",
			L"it is true",
			L"it is useful",
			L"it would be ",
			L"let's be clear",
			L"needless to say",
			L"of less importance",
			L"on account of",
			L"on the contrary",
			L"on the whole",
			L"so as to",
			L"so long as",
			L"some of the",
			L"the basic idea",
			L"the concept of",
			L"the fact is",
			L"the fact that",
			L"the final one",
			L"the first one",
			L"the idea of",
			L"the last one",
			L"the purpose of",
			L"the second one",
			L"the thing is ",
			L"there has been",
			L"there have been",
			L"to be frankly",
			L"to be honest",
			L"to be sure",
			L"to begin with",
			L"to start with",
			L"to sum up",
			L"under the circumstances",
			L"under those circumstances",
			L"whatever might happen",
			L"when in fact",
			L"while in fact",
			L"with regards to",
			L"with the assumption"
		},

		{
			L"all else being equal",
			L"as a final point",
			L"as far, as to ",
			L"as I was saying",
			L"at the present time",
			L"at the same time",
			L"as was stated before",
			L"back to our topic",
			L"by the same token",
			L"during the course of",
			L"for all practical purposes",
			L"for the most part",
			L"for the purpose of",
			L"for the purposes of",
			L"for the reason that",
			L"for what it's worth",
			L"here is the thing",
			L"here is the deal",
			L"in a similar way",
			L"in my humble opinion",
			L"in the first place",
			L"in the same way",
			L"in the second place",
			L"in the third place",
			L"it has been shown",
			L"it would have been",
			L"it’s difficult to say",
			L"it's important to note",
			L"last but not least",
			L"let us be clear",
			L"on a regular basis ",
			L"on the condition that",
			L"on the other hand",
			L"on the subject of",
			L"returning to the subject",
			L"that being the case",
			L"time and time again",
			L"to put it another way",
			L"to the end that",
			L"what this means is",
			L"when it comes to",
			L"with this in mind"
		},

		{
			L"as a matter of fact",
			L"as far as I’m concerned ",
			L"as has been noted",
			L"at this point in time",
			L"be that as it may",
			L"due to the fact that",
			L"for all intents and purposes",
			L"for what it is worth",
			L"it is difficult to say",
			L"it is important to note",
			L"let me be very clear",
			L"the fact of the matter",
			L"the first step is to ",
			L"what I want to say",
			L"with this fact in mind"
		},

		{
			L"as far as I am concerned",
			L"at the end of the day",
			L"in spite of that fact that",
			L"the point I want to make	",
			L"to cut a long story short",
			L"to put it in a nutshell",
			L"to spell it out in detail"
		}

	};

}

#endif
