#ifndef WORDS_EN
#define WORDS_EN

#include "definitions.hpp"

// expression list, divided by word count
// alphabetical sorting is for convenience only and has no impact on the process

namespace fillw
{
	inline word_list_type word_list_en = 
	{
		{
			L"absolutely",
			L"accordingly",
			L"actual",
			L"actually",
			L"additionally",
			L"admittedly",
			L"afterwards",
			L"almost",
			L"already",
			L"also",
			L"alternatively",
			L"although",
			L"altogether",
			L"always",
			L"amazing",
			L"another",
			L"any",
			L"anyhow",
			L"anyway",
			L"anywhere",
			L"apparently",
			L"approximately",
			L"approximatively",
			L"assuredly",
			L"awful",
			L"bad",
			L"badly",
			L"barely",
			L"basically",
			L"beautiful",
			L"beautifully",
			L"because",
			L"begin",
			L"besides",
			L"best",
			L"better",
			L"big",
			L"bigger",
			L"biggest",
			L"bit",
			L"briefly",
			L"but",
			L"can",
			L"can't",
			L"certain",
			L"certainly",
			L"circa",
			L"clear",
			L"clearly",
			L"close",
			L"closely",
			L"closer",
			L"closest",
			L"coincidentally",
			L"common",
			L"commonly",
			L"completely",
			L"complicated",
			L"concerning",
			L"consequently",
			L"considering",
			L"contrary",
			L"conversely",
			L"corresponding",
			L"could",
			L"couldn't",
			L"could've",
			L"deeply",
			L"definitely",
			L"despite",
			L"different",
			L"differently",
			L"disastrous",
			L"disastrously",
			L"doubtless",
			L"doubtlessly",
			L"easier",
			L"easiest",
			L"easy",
			L"easily",
			L"effective",
			L"effectively",
			L"either",
			L"enormous",
			L"enormously",
			L"enough",
			L"entirely",
			L"equally",
			L"especially",
			L"essentially",
			L"et cetera",
			L"etc",
			L"even",
			L"eventually",
			L"exactly",
			L"extremely",
			L"faint",
			L"faintly",
			L"fairly",
			L"few",
			L"finally",
			L"fine",
			L"frankly",
			L"frequently",
			L"full",
			L"fully",
			L"further",
			L"furthermore",
			L"general",
			L"generally",
			L"good",
			L"great",
			L"greeter",
			L"greatest",
			L"happily",
			L"hard",
			L"hardly",
			L"heavy",
			L"heavily",
			L"hence",
			L"here",
			L"here's",
			L"hereby",
			L"herewith",
			L"high",
			L"highly",
			L"hopefully",
			L"horrible",
			L"horribly",
			L"horrid",
			L"however",
			L"huge",
			L"hugely",
			L"I",
			L"I'm",
			L"I've",
			L"imprecise",
			L"improper",
			L"inaccurate",
			L"inaccurately",
			L"inadequate",
			L"inadequately",
			L"inasmuch",
			L"incidentally",
			L"indeed",
			L"indefinite",
			L"inexact",
			L"inexactly",
			L"initially",
			L"insignificant",
			L"insignificantly",
			L"insofar",
			L"intense",
			L"intensely",
			L"it's",
			L"just",
			L"known",
			L"large",
			L"largely",
			L"larger",
			L"largest",
			L"lastly",
			L"lightly",
			L"like",
			L"likewise",
			L"little",
			L"literal",
			L"literally",
			L"loose",
			L"loosely",
			L"lot",
			L"lots",
			L"low",
			L"many",
			L"marginally",
			L"massive",
			L"massively",
			L"may",
			L"maybe",
			L"might",
			L"mild",
			L"mildly",
			L"mine",
			L"more",
			L"moreover",
			L"most",
			L"mostly",
			L"much",
			L"multiple",
			L"my",
			L"namely",
			L"naturally",
			L"near",
			L"nearly",
			L"necessary",
			L"necessarily",
			L"negligible",
			L"negligibly",
			L"nevertheless",
			L"next",
			L"nice",
			L"nicer",
			L"nicest",
			L"nicely",
			L"nonetheless",
			L"notably",
			L"notwithstanding",
			L"numerous",
			L"obviously",
			L"occasionally",
			L"often",
			L"ok",
			L"okay",
			L"only",
			L"otherwise",
			L"our",
			L"ours",
			L"overall",
			L"particular",
			L"particularly",
			L"perhaps",
			L"plenty",
			L"poorly",
			L"possible",
			L"possibly",
			L"practical",
			L"practically",
			L"preferably",
			L"previously",
			L"primarily",
			L"probably",
			L"properly",
			L"precisely",
			L"pretty",
			L"quite",
			L"rarely",
			L"rather",
			L"real",
			L"really",
			L"recently",
			L"regarding",
			L"regardless",
			L"relatively",
			L"relevant",
			L"right",
			L"scarcely",
			L"secondly",
			L"seriously",
			L"severe",
			L"severely",
			L"should",
			L"shouldn't",
			L"should've",
			L"significantly",
			L"similarly",
			L"simple",
			L"simpler",
			L"simplest",
			L"simply",
			L"since",
			L"slight",
			L"slightly",
			L"small",
			L"smaller",
			L"smallest",
			L"so",
			L"some",
			L"somehow",
			L"someplace",
			L"sometimes",
			L"somewhat",
			L"somewhere",
			L"soon",
			L"sparse",
			L"sparsely",
			L"specifically",
			L"start",
			L"still",
			L"strong",
			L"stronger",
			L"strongest",
			L"strongly",
			L"stuff",
			L"subsequently",
			L"suitable",
			L"summarizing",
			L"sure",
			L"surely",
			L"tall",
			L"taller",
			L"tallest",
			L"technically",
			L"terrible",
			L"terribly",
			L"terrific",
			L"that",
			L"that's",
			L"there",
			L"there's",
			L"therefore",
			L"therein",
			L"thereto",
			L"thereunto",
			L"they're",
			L"they've",
			L"thing",
			L"things",
			L"thirdly",
			L"this",
			L"those",
			L"though",
			L"thus",
			L"tolerable",
			L"tolerably",
			L"too",
			L"totally",
			L"traditionally",
			L"tremendous",
			L"tremendously",
			L"truly",
			L"try",
			L"typical",
			L"typically",
			L"ultimately",
			L"uncommon",
			L"undoubtedly",
			L"unless",
			L"unprecise",
			L"unusual",
			L"unusually",
			L"us",
			L"using",
			L"usual",
			L"usually",
			L"vague",
			L"vaguely",
			L"various",
			L"versus",
			L"very",
			L"virtually",
			L"we",
			L"we're",
			L"we've",
			L"weak",
			L"weakly",
			L"well",
			L"whatever",
			L"whenever",
			L"whereas",
			L"wherever",
			L"while",
			L"whoever",
			L"wide",
			L"widely",
			L"wider",
			L"widest",
			L"won't",
			L"worse",
			L"worst",
			L"would",
			L"wouldn't",
			L"would've",
			L"yet",
			L"you",
			L"you're",
			L"you've",
			L"your",
			L"yours",
		},
		{
			L"a few",
			L"a little",
			L"a lot",
			L"above all",
			L"according to",
			L"adjacent to",
			L"after all",
			L"along with",
			L"and yet",
			L"apart from",
			L"are shown",
			L"are presented",
			L"as against",
			L"as being",
			L"as discussed",
			L"as exemplified",
			L"as explained",
			L"as for",
			L"as illustrated",
			L"as mentioned",
			L"as of",
			L"as said",
			L"as shown",
			L"as stated",
			L"as well",
			L"as yet",
			L"at least",
			L"at length",
			L"be said",
			L"be seen",
			L"be shown",
			L"because of",
			L"but also",
			L"by contrast",
			L"can be",
			L"compared to",
			L"considering this",
			L"could possibly",
			L"due to",
			L"either way",
			L"even if",
			L"even more",
			L"even so",
			L"even though",
			L"following the",
			L"following this",
			L"for certain",
			L"for example",
			L"for instance",
			L"for sure",
			L"given that",
			L"granted that",
			L"granting that",
			L"great number",
			L"if so",
			L"in addition",
			L"in brief ",
			L"in case",
			L"in conclusion",
			L"in contrast",
			L"in detail",
			L"in fact",
			L"in general",
			L"in particular",
			L"is presented",
			L"in short",
			L"in summary",
			L"is described",
			L"is known",
			L"is possible",
			L"is shown",
			L"is used",
			L"inasmuch as",
			L"kind of",
			L"large number",
			L"looking at",
			L"more importantly",
			L"more specifically",
			L"most importantly",
			L"neighboring on",
			L"next chapter",
			L"next page",
			L"not only",
			L"of course",
			L"once again",
			L"only if",
			L"on one hand",
			L"opposite to",
			L"outside of",
			L"owing to",
			L"prior to",
			L"provided that",
			L"scores of",
			L"show that",
			L"shows that",
			L"sort of",
			L"so that",
			L"such as",
			L"such that",
			L"taken together",
			L"that is",
			L"that means",
			L"the goal",
			L"the purpose",
			L"this approach",
			L"this chapter",
			L"this is",
			L"this means",
			L"this method",
			L"this project",
			L"this research",
			L"this section",
			L"this work",
			L"thus to",
			L"to clarify",
			L"to conclude",
			L"to demonstrate",
			L"to explain",
			L"to illustrate",
			L"to repeat",
			L"to resume",
			L"to this",
			L"used to",
			L"was shown",
			L"was used",
			L"whatever happens",
			L"will be",
			L"with reference",
			L"with this",
			L"without doubt",
			L"would be",
			L"you know",
			L"you see",
		},
		{
			L"all the same",
			L"and so forth",
			L"and so on",
			L"as a consequence",
			L"as a result",
			L"as an illustration",
			L"as far as",
			L"as long as",
			L"as opposed to",
			L"as to whether",
			L"as was mentioned",
			L"as was said",
			L"as was shown",
			L"as was stated",
			L"as well as",
			L"as stated before",
			L"at all times",
			L"at any rate",
			L"by means of",
			L"by the way",
			L"each and every",
			L"first of all ",
			L"for the purpose of",
			L"for this reason",
			L"for these reasons",
			L"given these points",
			L"here’s the thing",
			L"here's the deal",
			L"I might add",
			L"in a nutshell",
			L"in a word ",
			L"in addition to",
			L"in all cases",
			L"in any case",
			L"in any event",
			L"in both cases",
			L"in like manner",
			L"in my opinion",
			L"in our opinion",
			L"in order that",
			L"in order to",
			L"in other words",
			L"in other terms",
			L"in some degree",
			L"in similar fashion",
			L"in spite of",
			L"in terms of",
			L"in that case",
			L"in the assumption",
			L"in the case",
			L"in the event",
			L"in the end",
			L"in the hope",
			L"in the meantime",
			L"in the process",
			L"in this case",
			L"in this context",
			L"in this thesis",
			L"in this work",
			L"in view of",
			L"it is true",
			L"it is useful",
			L"it would be ",
			L"let's be clear",
			L"more or less",
			L"needless to say",
			L"of less importance",
			L"on account of",
			L"on the contrary",
			L"on the whole",
			L"so as to",
			L"so long as",
			L"some of the",
			L"the basic idea",
			L"the concept of",
			L"the fact is",
			L"the fact that",
			L"the final one",
			L"the first one",
			L"the idea of",
			L"the last one",
			L"the purpose of",
			L"the second one",
			L"the thing is ",
			L"there has been",
			L"there have been",
			L"this is where",
			L"to be frankly",
			L"to be honest",
			L"to be sure",
			L"to begin with",
			L"to start with",
			L"to some degree",
			L"to some extent",
			L"to sum up",
			L"under the circumstances",
			L"under those circumstances",
			L"whatever might happen",
			L"when in fact",
			L"while in fact",
			L"with regards to",
			L"with the assumption",
		},
		{
			L"all else being equal",
			L"as a final point",
			L"as far, as to ",
			L"as I was saying",
			L"at the present time",
			L"at the same time",
			L"as was stated before",
			L"back to our topic",
			L"by the same token",
			L"during the course of",
			L"end of the day",
			L"for all practical purposes",
			L"for the most part",
			L"for the purpose of",
			L"for the purposes of",
			L"for the reason that",
			L"for what it's worth",
			L"here is the thing",
			L"here is the deal",
			L"in a similar way",
			L"in my humble opinion",
			L"in the first place",
			L"in the same way",
			L"in the second place",
			L"in the third place",
			L"it has been shown",
			L"it would have been",
			L"it is difficult to",
			L"it is important to",
			L"last but not least",
			L"let us be clear",
			L"on a regular basis ",
			L"on the condition that",
			L"on the other hand",
			L"on the subject of",
			L"returning to the subject",
			L"that being the case",
			L"time and time again",
			L"to put it another way",
			L"to the end that",
			L"what this means is",
			L"when it comes to",
			L"with the aid of",
			L"with the help of",
			L"with this in mind",
		},
		{
			L"as a matter of fact",
			L"as far as I’m concerned ",
			L"as has been noted",
			L"at this point in time",
			L"be that as it may",
			L"due to the fact that",
			L"for all intents and purposes",
			L"for what it is worth",
			L"let me be very clear",
			L"the fact of the matter",
			L"the first step is to ",
			L"what I want to say",
			L"with this fact in mind",
		}
	};
}

#endif
