#ifndef WORDS_DE
#define WORDS_DE

#include "definitions.hpp"

namespace fillw
{

	inline word_list_type word_list_de = 

	{
		{
			L"aber",
			L"abermals",
			L"ähnlich",
			L"allein",
			L"allemal",
			L"allenfalls",
			L"allenthalben",
			L"allerdings",
			L"allesamt",
			L"allgemein",
			L"allmählich",
			L"allzu",
			L"also",
			L"alt",
			L"andauernd",
			L"andererseits",
			L"andernfalls",
			L"anscheinend",
			L"auch",
			L"auffallend",
			L"aufgrund",
			L"augenscheinlich",
			L"ausdrücklich",
			L"außerdem",
			L"ausgerechnet",
			L"ausnahmslos",
			L"ausreichend",
			L"bald",
			L"beide",
			L"beiden",
			L"beiderlei",
			L"beides",
			L"beinahe",
			L"bekanntlich",
			L"besonders",
			L"besser",
			L"bestenfalls",
			L"bestimmt",
			L"beträchtlich",
			L"bevor",
			L"bezüglich",
			L"bisher",
			L"bislang",
			L"bloß",
			L"da",
			L"dabei",
			L"dadurch",
			L"dafür",
			L"dagegen",
			L"daher",
			L"dahin",
			L"damals",
			L"damit",
			L"danach",
			L"daneben",
			L"dank",
			L"dann",
			L"daran",
			L"darauf",
			L"daraus",
			L"dargestellt",
			L"darin",
			L"darum",
			L"davon",
			L"davor",
			L"dazu",
			L"demgegenüber",
			L"demgemäß",
			L"demnach",
			L"demselben",
			L"denn",
			L"dennoch",
			L"derart",
			L"derartig",
			L"deshalb",
			L"desto",
			L"desungeachtet",
			L"deswegen",
			L"diesmal",
			L"direkt",
			L"direkte",
			L"direkten",
			L"direkter",
			L"doch",
			L"drittens",
			L"durchaus",
			L"durchweg",
			L"eben",
			L"ebenfalls",
			L"ebenso",
			L"eh",
			L"ehe",
			L"eher",
			L"eigenen",
			L"eigenes",
			L"eigentlich",
			L"einerseits",
			L"einfach",
			L"einige",
			L"einigermaßen",
			L"einmal",
			L"entsprechend",
			L"erst",
			L"erstens",
			L"etliche",
			L"etwa",
			L"etwas",
			L"fast",
			L"förmlich",
			L"freilich",
			L"ganz",
			L"gänzlich",
			L"gar",
			L"gefälligst",
			L"gelegentlich",
			L"gemeinhin",
			L"genau",
			L"genug",
			L"geradezu",
			L"gern",
			L"gewiss",
			L"gewisse",
			L"gewissermaßen",
			L"glatt",
			L"gleich",
			L"gleichsam",
			L"gleichwohl",
			L"gleichzeitig",
			L"glücklicherweise",
			L"größtenteils",
			L"gut",
			L"gute",
			L"gutem",
			L"guten",
			L"guter",
			L"gutes",
			L"halt",
			L"hätte",
			L"häufig",
			L"herein",
			L"hierbei",
			L"hiermit",
			L"hiesige",
			L"hingegen",
			L"hinlänglich",
			L"hinrechend"
			L"hinterher",
			L"höchst",
			L"höchstens",
			L"ich",
			L"immer",
			L"immerhin",
			L"immerzu",
			L"indessen",
			L"infolge",
			L"infolgedessen",
			L"innen",
			L"innerhalb",
			L"insbesondere",
			L"insofern",
			L"inzwischen",
			L"irgend",
			L"irgendein",
			L"irgendeine",
			L"irgendjemand",
			L"irgendwann",
			L"irgendwas",
			L"irgendwen",
			L"irgendwer",
			L"irgendwie",
			L"irgendwo",
			L"ja",
			L"je",
			L"jedenfalls",
			L"jedoch",
			L"jemals",
			L"jetzt",
			L"kaum",
			L"keinesfalls",
			L"keineswegs",
			L"konkret",
			L"konkrete",
			L"konkreten",
			L"konkreter",
			L"konkretes",
			L"künftig",
			L"könne",
			L"könnte",
			L"könnten",
			L"könntest",
			L"längst",
			L"längstens",
			L"lassen",
			L"lediglich",
			L"leider",
			L"letztendlich",
			L"letztlich",
			L"mal",
			L"man",
			L"mancherorts",
			L"manches",
			L"manchmal",
			L"mehrfach",
			L"mein",
			L"meine",
			L"meinem",
			L"meiner",
			L"meines",
			L"meinetwegen",
			L"meins",
			L"meist",
			L"meistens",
			L"meistenteils",
			L"mindestens",
			L"mir",
			L"mithin",
			L"mitunter",
			L"möglich",
			L"mögliche",
			L"möglichen",
			L"möglicher",
			L"möglicherweise",
			L"möglichst",
			L"müsse",
			L"nämlich",
			L"naturgemäß",
			L"natürlich",
			L"neuerdings",
			L"neuerlich",
			L"neulich",
			L"nichtsdestotrotz",
			L"nichtsdestoweniger",
			L"nötigenfalls",
			L"nun",
			L"nunmehr",
			L"obwohl",
			L"oder",
			L"offenbar",
			L"offenkundig",
			L"offensichtlich",
			L"oft",
			L"ohnedies",
			L"partout",
			L"persönlich",
			L"plötzlich",
			L"praktisch",
			L"prinzipiell",
			L"quasi",
			L"recht",
			L"reichlich",
			L"reiflich",
			L"relativ",
			L"restlos",
			L"richtiggehend",
			L"riesig",
			L"rundheraus",
			L"rundum",
			L"samt",
			L"sämtliche",
			L"sattsam",
			L"schlecht",
			L"schlechte",
			L"schlechtem",
			L"schlechten",
			L"schlecter",
			L"schlechtes",
			L"schlicht",
			L"schlichtweg",
			L"schließlich",
			L"schlussendlich",
			L"schon",
			L"schwerlich",
			L"schwierig",
			L"sehr",
			L"sei",
			L"seien",
			L"selber",
			L"selbst",
			L"selbstredend",
			L"selbstverständlich",
			L"selten",
			L"seltsamerweise",
			L"sicher",
			L"sicherlich",
			L"so",
			L"sogar",
			L"soll",
			L"sollte",
			L"sollten",
			L"solltest",
			L"sonst",
			L"sowieso",
			L"sozusagen",
			L"stellenweise",
			L"stets",
			L"tatsächlich",
			L"tatsächlichen",
			L"tatsächlicher",
			L"tatsächliches",
			L"total",
			L"trotz",
			L"trotzdem",
			L"überaus",
			L"überdies",
			L"überhaupt",
			L"übrigens",
			L"umständehalber",
			L"unbedingt",
			L"ungemein",
			L"uns",
			L"unser",
			L"unsere",
			L"unserem",
			L"unserer",
			L"unseres",
			L"vergleichsweise",
			L"vermutlich",
			L"viel",
			L"vielfach",
			L"vielleicht",
			L"viertens",
			L"voll",
			L"vollends",
			L"völlig",
			L"vollkommen",
			L"vollständig",
			L"vorzufinden",
			L"wahrscheinlich",
			L"wäre",
			L"wären",
			L"wärest",
			L"weitem",
			L"weiter",
			L"weitere",
			L"weiterem",
			L"weiteren",
			L"weiterer",
			L"weiteres",
			L"weiterhin",
			L"weitgehend",
			L"welche",
			L"welchem",
			L"welchen",
			L"welcher",
			L"wenig",
			L"wenige",
			L"weniger",
			L"wenigstens",
			L"wenn",
			L"wenngleich",
			L"werde",
			L"werden",
			L"weshalb",
			L"wieder",
			L"wiederum",
			L"wiewohl",
			L"wir",
			L"wirklich",
			L"wodurch",
			L"wogegen",
			L"woher",
			L"wohin",
			L"wohingegen",
			L"wohl",
			L"wohlgemerkt",
			L"wohlweislich",
			L"wollen",
			L"wollt",
			L"wollte",
			L"wollten",
			L"wolltest",
			L"wolltet",
			L"womit",
			L"womöglich",
			L"woraufhin",
			L"woraus",
			L"worin",
			L"wurde",
			L"wurden"
			L"würde",
			L"würden",
			L"würdest",
			L"zahlreich",
			L"zeige",
			L"zeitweise",
			L"ziemlich",
			L"zudem",
			L"zugegeben",
			L"zumeist",
			L"zusehends",
			L"zusehens",
			L"zuweilen",
			L"zwar",
			L"zweifellos",
			L"zweifelsfrei",
			L"zweifelsohne",
			L"zweitens",
			L"zusammenfassend"
		},
		
		{
			L"als Beispiel",
			L"an sich",
			L"aufs neue",
			L"bei Weitem",
			L"befindet sich",
			L"dargestellt ist",
			L"das Ganze",
			L"des Öfteren",
			L"dieser Arbeit",
			L"diesem Kapitel",
			L"diesem Projekt",
			L"dort ist",
			L"ein Beispiel",
			L"ein bisschen",
			L"ein wenig",
			L"ergibt sich",
			L"es kann",
			L"gar nicht",
			L"gezeigt wurde",
			L"hier ist",
			L"im Allgemeinen",
			L"im Folgenden",
			L"im Prinzip",
			L"lassen sich",
			L"lässt sich",
			L"meines Erachtens",
			L"ohne Weiteres",
			L"ohne Zweifel",
			L"von Neuem",
			L"zeigt, dass",
			L"zum Teil"
		},

		{
			L"allem Anschein nach",
			L"alles in allem",
			L"Aufgabe ist es",
			L"dann und wann",
			L"das führt dazu",
			L"der Vorteil in",
			L"der Zweck ist",
			L"der Zweck liegt",
			L"ein Beispiel für",
			L"es ergeben sich",
			L"es ergibt sich",
			L"für den Fall",
			L"für sich genommen",
			L"Gang und Gäbe",
			L"ganz und gar",
			L"handelt es sich",
			L"hat die Aufgabe",
			L"hat das Ziel",
			L"hier und da",
			L"im Grunde genommen",
			L"im nächsten Schritt",
			L"in der Tat",
			L"in der Regel",
			L"in diesem Fall",
			L"in diesen Fällen",
			L"in diesem Zusammenhang",
			L"in unserem Fall",
			L"in unserer Arbeit",
			L"ist es Aufgabe",
			L"ist es Ziel",
			L"ist zu sehen",
			L"mehr oder weniger",
			L"meiner Meinung nach",
			L"mit großer Wahrscheinlichkeit",
			L"samt und sonders",
			L"sowohl als auch",
			L"unserer Meinung nach",
			L"voll und ganz",
			L"warum auch immer",
			L"weshalb auch immer",
			L"wieso auch immer",
			L"Ziel ist es",
			L"zu sehen ist",
			L"zur Verwendung kommt"
		}
	};

}

#endif
