#ifndef WORDS_DE
#define WORDS_DE

#include "definitions.hpp"

// expression list, divided by word count
// alphabetical sorting is for convenience only and has no impact on the process
// use lower case letters to minimize lower casing issues due to locale and encoding

namespace fillw
{
    inline word_list_type word_list_de = 
    {
        {
            L"aber",
            L"abermals",
            L"ähnlich",
            L"ähnliche",
            L"ähnlichem",
            L"ähnlichen",
            L"ähnlicher",
            L"ähnliches",
            L"ähnlichste",
            L"ähnlichstem",
            L"ähnlichsten",
            L"ähnlichster",
            L"ähnlichstes",
            L"aktuell",
            L"aktuelle",
            L"aktuellem",
            L"aktuellem",
            L"aktueller",
            L"aktuelles",
            L"alle",
            L"allem",
            L"allen",
            L"aller",
            L"alles",
            L"allein",
            L"alleine",
            L"alleinig",
            L"allemal",
            L"allenfalls",
            L"allenthalben",
            L"allerdings",
            L"allesamt",
            L"allgemein",
            L"allgemeine",
            L"allgemeinem",
            L"allgemeinen",
            L"allgemeiner",
            L"allgemeines",
            L"allmählich",
            L"allzu",
            L"also",
            L"alt",
            L"alte",
            L"altem",
            L"alten",
            L"alter",
            L"altes",
            L"andauernd",
            L"andauernde",
            L"andauerndem",
            L"andauernden",
            L"andauernder",
            L"andauerndes",
            L"andererseits",
            L"andernfalls",
            L"anders",
            L"andere",
            L"anderem",
            L"anderen",
            L"anderer",
            L"anderes",
            L"annähernd",
            L"ansonsten",
            L"anscheinend",
            L"anstatt",
            L"auch",
            L"auffallend",
            L"auffallende",
            L"auffallendem",
            L"auffallenden",
            L"auffallender",
            L"auffallendes",
            L"aufgrund",
            L"augenscheinlich",
            L"ausdrücklich",
            L"außerdem",
            L"ausgerechnet",
            L"ausnahmslos",
            L"ausreichend",
            L"ausreichende",
            L"ausreichendem",
            L"ausreichenden",
            L"ausreichender",
            L"ausreichendes",
            L"ausschließlich",
            L"bald",
            L"baldig",
            L"baldige",
            L"baldigem",
            L"baldigen",
            L"baldiger",
            L"baldiges",
            L"beide",
            L"beidem",
            L"beiden",
            L"beider",
            L"beides",
            L"beiderlei",
            L"beides",
            L"beinahe",
            L"beispielsweise",
            L"bekannt",
            L"bekannte",
            L"bekanntem",
            L"bekannten",
            L"bekannter",
            L"bekanntes",
            L"bekanntlich",
            L"bemerkbar",
            L"bemerkbare",
            L"bemerkbarem",
            L"bemerkbaren",
            L"bemerkbarer",
            L"bemerkbares",
            L"benutzen",
            L"benutzt",
            L"benutzte",
            L"benutztem",
            L"benutzten",
            L"benutzter",
            L"benutztes",
            L"bereit",
            L"beschreiben",
            L"beschreibt",
            L"beschrieb",
            L"beschrieben",
            L"beschriebene",
            L"beschriebenem",
            L"beschriebenen",
            L"beschriebener",
            L"beschriebenes",
            L"besondere",
            L"besonders",
            L"besser",
            L"bessere",
            L"besserem",
            L"besseren",
            L"besserer",
            L"besseres",
            L"bestenfalls",
            L"bestem",
            L"besten",
            L"bestens",
            L"bester",
            L"bestes",
            L"bestimmt",
            L"bestimmte",
            L"bestimmtem",
            L"bestimmten",
            L"bestimmter",
            L"bestimmtes",
            L"beträchtlich",
            L"beträchtliche",
            L"beträchtlichem",
            L"beträchtlichen",
            L"beträchtlicher",
            L"beträchtliches",
            L"bevor",
            L"beziehungsweise",
            L"bezüglich",
            L"bisher",
            L"bisherig",
            L"bisherige",
            L"bisherigem",
            L"bisherigen",
            L"bisheriger",
            L"bisheriges",
            L"bislang",
            L"bisschen",
            L"bloß",
            L"bloße",
            L"bloßem",
            L"bloßen",
            L"bloßer",
            L"bloßes",
            L"bruchteil",
            L"bruchteilen",
            L"bzw",
            L"circa",
            L"da",
            L"dabei",
            L"dadurch",
            L"dafür",
            L"dagegen",
            L"daher",
            L"dahin",
            L"damalige",
            L"damals",
            L"damit",
            L"danach",
            L"daneben",
            L"dank",
            L"dann",
            L"daran",
            L"darauf",
            L"daraus",
            L"dargestellt",
            L"dargestellte",
            L"dargestelltem",
            L"dargestellten",
            L"dargestellter",
            L"dargestelltes",
            L"darin",
            L"darum",
            L"dass",
            L"davon",
            L"davor",
            L"dazu",
            L"demgegenüber",
            L"demgemäß",
            L"demnach",
            L"demselben",
            L"denn",
            L"dennoch",
            L"derart",
            L"derartig",
            L"derartige",
            L"derartigem",
            L"derartigen",
            L"derartiger",
            L"derartiges",
            L"dergleichen",
            L"derselbe",
            L"derselben",
            L"desgleichen",
            L"deshalb",
            L"desselben",
            L"desto",
            L"desungeachtet",
            L"deswegen",
            L"deutlich",
            L"deutliche",
            L"deutlichem",
            L"deutlichen",
            L"deutlicher",
            L"deutliches",
            L"dies",
            L"diesmal",
            L"dieselbe",
            L"dieselben",
            L"direkt",
            L"direkte",
            L"direkten",
            L"direkter",
            L"divers",
            L"diverse",
            L"diversem",
            L"diversen",
            L"diverser",
            L"diverses",
            L"doch",
            L"dort",
            L"dortig",
            L"dortige",
            L"dortigem",
            L"dortigen",
            L"dortiger",
            L"dortiges",
            L"dringlich",
            L"dringlichst",
            L"drittens",
            L"drüben",
            L"durch",
            L"durchaus",
            L"durchweg",
            L"eben",
            L"ebenfalls",
            L"ebenso",
            L"eh",
            L"ehe",
            L"eher",
            L"eigenartig",
            L"eigenartige",
            L"eigenartigem",
            L"eigenartigen",
            L"eigenartiger",
            L"eigenartiges",
            L"eigene",
            L"eigenen",
            L"eigener",
            L"eigenes",
            L"eigentlich",
            L"eigentliche",
            L"eigentlichem",
            L"eigentlichen",
            L"eigentlicher",
            L"eigentliches",
            L"einerseits",
            L"einfach",
            L"einfache",
            L"einfachem",
            L"einfachen",
            L"einfacher",
            L"einfachere",
            L"einfacherem",
            L"einfacheren",
            L"einfacheres",
            L"einfaches",
            L"einfachheitshalber",
            L"einfachste",
            L"einfachstem",
            L"einfachsten",
            L"einfachster",
            L"einfachstes",
            L"einige",
            L"einigem",
            L"einigen",
            L"einiger",
            L"einiges",
            L"einigermaßen",
            L"einmal",
            L"einmalig",
            L"einmalige",
            L"einmaligem",
            L"einmaligen",
            L"einmaliger",
            L"einmaliges",
            L"einzigartig",
            L"einzigartige",
            L"einzigartigem",
            L"einzigartigen",
            L"einzigartiger",
            L"einzigartiges",
            L"enorm",
            L"enorme",
            L"enormem",
            L"enormen",
            L"enormer",
            L"enormes",
            L"entsprechend",
            L"entsprechende",
            L"entsprechender",
            L"entsprechendes",
            L"erfolgen",
            L"erfolgt",
            L"erfolgte",
            L"erfolgtem",
            L"erfolgten",
            L"erfolgter",
            L"erfolgtes",
            L"erst",
            L"erstens",
            L"et cetera",
            L"etc",
            L"etliche",
            L"etlichem",
            L"etlichen",
            L"etlicher",
            L"etliches",
            L"etwa",
            L"etwaige",
            L"etwas",
            L"fast",
            L"fix",
            L"förmlich",
            L"freilich",
            L"früher",
            L"ganz",
            L"gänzlich",
            L"gar",
            L"gefälligst",
            L"geeignet",
            L"geeignete",
            L"geeignetem",
            L"geeigneten",
            L"geeigneter",
            L"geeignetere",
            L"geeigneterem",
            L"geeigneteren",
            L"geeigneteres",
            L"geeignetes",
            L"geeignetste",
            L"geeignetstem",
            L"geeignetsten",
            L"geeignetster",
            L"geeignetstes",
            L"gelegentlich",
            L"gemeinhin",
            L"genau",
            L"genaue",
            L"genauem",
            L"genauen",
            L"genauer",
            L"genauere",
            L"genauerem",
            L"genaueren",
            L"genauerer",
            L"genaueres",
            L"genaues",
            L"genauste",
            L"genaustem",
            L"genausten",
            L"genauster",
            L"genaustes",
            L"genug",
            L"genügend",
            L"genügt",
            L"genügte",
            L"genügten",
            L"geradezu",
            L"gern",
            L"gerne",
            L"gesamte",
            L"gesamtem",
            L"gesamten",
            L"gesamter",
            L"gesamtes",
            L"gewiss",
            L"gewisse",
            L"gewissem",
            L"gewissen",
            L"gewisser",
            L"gewisses",
            L"gewissermaßen",
            L"glatt",
            L"gleich",
            L"gleiche",
            L"gleichem",
            L"gleichen",
            L"gleicher",
            L"gleiches",
            L"gleichsam",
            L"gleichwohl",
            L"gleichzeitig",
            L"gleichzeitige",
            L"gleichzeitigem",
            L"gleichzeitigen",
            L"gleichzeitiger",
            L"gleichzeitiges",
            L"glücklicherweise",
            L"groß",
            L"große",
            L"großem",
            L"großen",
            L"großer",
            L"größer",
            L"größere",
            L"größerem",
            L"größeren",
            L"größeres",
            L"großes",
            L"größtenteils",
            L"gut",
            L"gute",
            L"gutem",
            L"guten",
            L"guter",
            L"gutes",
            L"halt",
            L"hätte",
            L"häufig",
            L"häufige",
            L"häufigem",
            L"häufigen",
            L"häufiger",
            L"häufiges",
            L"häufigste",
            L"häufigstem",
            L"häufigsten",
            L"häufigster",
            L"häufigstes",
            L"herein",
            L"hier",
            L"hierbei",
            L"hierfür",
            L"hiermit",
            L"hierzu",
            L"hiesige",
            L"hingegen",
            L"hinlänglich",
            L"hinreichend",
            L"hinreichende",
            L"hinreichendem",
            L"hinreichenden",
            L"hinreichender",
            L"hinreichendes",
            L"hinterher",
            L"hoch",
            L"höchst",
            L"höchste",
            L"höchstem",
            L"höchsten",
            L"höchstens",
            L"höchster",
            L"höchstes",
            L"hochwertig",
            L"hochwertige",
            L"hochwertigem",
            L"hochwertigen",
            L"hochwertiger",
            L"hochwertiges",
            L"hochwertigste",
            L"hochwertigstem",
            L"hochwertigsten",
            L"hochwertigster",
            L"hochwertigstes",
            L"hohe",
            L"hohem",
            L"hohen",
            L"hoher",
            L"hohes",
            L"höhere",
            L"höherem",
            L"höheren",
            L"höherer",
            L"höheres",
            L"hoffe",
            L"hoffen",
            L"hoffentlich",
            L"hoffst",
            L"hofft",
            L"ich",
            L"immer",
            L"immerhin",
            L"immerzu",
            L"immense",
            L"indessen",
            L"infolge",
            L"infolgedessen",
            L"innen",
            L"innerhalb",
            L"insbesondere",
            L"insgesamt",
            L"insofern",
            L"inzwischen",
            L"irgend",
            L"irgendein",
            L"irgendeine",
            L"irgendeinem",
            L"irgendeinen",
            L"irgendeiner",
            L"irgendjemand",
            L"irgendwann",
            L"irgendwas",
            L"irgendwen",
            L"irgendwer",
            L"irgendwie",
            L"irgendwo",
            L"ja",
            L"je",
            L"jede",
            L"jeder",
            L"jedes",
            L"jedenfalls",
            L"jedoch",
            L"jemals",
            L"jetzt",
            L"jetzige",
            L"jetzigem",
            L"jetzigen",
            L"jetziger",
            L"jetziges",
            L"kann",
            L"kannst",
            L"kaum",
            L"keinesfalls",
            L"keineswegs",
            L"klar",
            L"klein",
            L"kleine",
            L"kleinem",
            L"kleinen",
            L"kleiner",
            L"kleinere",
            L"kleinerem",
            L"kleineren",
            L"kleineres",
            L"kleines",
            L"konkret",
            L"konkrete",
            L"konkretem",
            L"konkreten",
            L"konkreter",
            L"konkretes",
            L"konträr",
            L"konventionell",
            L"konventionelle",
            L"konventionellem",
            L"konventionellen",
            L"konventioneller",
            L"konventionelles",
            L"künftig",
            L"künftige",
            L"künftigem",
            L"künftigen",
            L"künftiger",
            L"künftiges",
            L"kurz",
            L"kurze",
            L"kurzem",
            L"kurzen",
            L"kurzer",
            L"kurzes",
            L"könne",
            L"können",
            L"könnte",
            L"könnten",
            L"könntest",
            L"langsam",
            L"längst",
            L"längste",
            L"längstem",
            L"längsten",
            L"längstens",
            L"längster",
            L"längstes",
            L"lassen",
            L"laute",
            L"lauten",
            L"lautet",
            L"lediglich",
            L"leicht",
            L"leichte",
            L"leichtem",
            L"leichten",
            L"leichter",
            L"leichtere",
            L"leichterem",
            L"leichteren",
            L"leichteres",
            L"leichtes",
            L"leider",
            L"letztendlich",
            L"letztens",
            L"letztlich",
            L"mal",
            L"man",
            L"mancherorts",
            L"manch",
            L"manche",
            L"manchem",
            L"manchen",
            L"mancher",
            L"manches",
            L"manchmal",
            L"mehr",
            L"mehrfach",
            L"mehrfache",
            L"mehrfachem",
            L"mehrfachen",
            L"mehrfacher",
            L"mehrfaches",
            L"mehrmals",
            L"mehrmalig",
            L"mehrmalige",
            L"mehrmaligem",
            L"mehrmaligen",
            L"mehrmaliges",
            L"mehrmaliger",
            L"mein",
            L"meine",
            L"meinem",
            L"meinen",
            L"meiner",
            L"meines",
            L"meinetwegen",
            L"meins",
            L"meist",
            L"meisten",
            L"meistens",
            L"meistenteils",
            L"merkbar",
            L"mich",
            L"mindestens",
            L"mir",
            L"mittels",
            L"mithilfe",
            L"mithin",
            L"mitunter",
            L"möglich",
            L"mögliche",
            L"möglichem",
            L"möglichen",
            L"möglicher",
            L"möglicherweise",
            L"möglichst",
            L"muss",
            L"müsse",
            L"müssen",
            L"musst",
            L"musste",
            L"müsste",
            L"mussten",
            L"müssten",
            L"müsstest",
            L"nachfolgend",
            L"nachfolgende",
            L"nachfolgenden",
            L"nachfolgenden",
            L"nachfolgender",
            L"nachfolgendes",
            L"nachteil",
            L"nachteile",
            L"nachteilen",
            L"näherungsweise",
            L"nämlich",
            L"naturgemäß",
            L"natürlich",
            L"neu",
            L"neue",
            L"neuem",
            L"neuen",
            L"neuer",
            L"neues",
            L"neuere",
            L"neuerem",
            L"neueren",
            L"neuerer",
            L"neueres",
            L"neuerdings",
            L"neuerlich",
            L"neulich",
            L"nichtsdestotrotz",
            L"nichtsdestoweniger",
            L"niedrig",
            L"niedrige",
            L"niedrigem",
            L"niedrigen",
            L"niedriger",
            L"niedriges",
            L"niedrigste",
            L"niedrigstem",
            L"niedrigsten",
            L"niedrigster",
            L"niedrigstes",
            L"nötigenfalls",
            L"nun",
            L"nunmehr",
            L"obwohl",
            L"oder",
            L"offenbar",
            L"offenkundig",
            L"offensichtlich",
            L"oft",
            L"öfter",
            L"öfters",
            L"ohnedies",
            L"ohnehin",
            L"optimal",
            L"optimale",
            L"optimalem",
            L"optimalen",
            L"optimaler",
            L"optimalere",
            L"optimalerem",
            L"optimaleren",
            L"optimaleres",
            L"optimales",
            L"optimalste",
            L"optimalstem",
            L"optimalsten",
            L"optimalster",
            L"optimalstes",
            L"partout",
            L"passend",
            L"passende",
            L"passendem",
            L"passenden",
            L"passender",
            L"passendes",
            L"passendste",
            L"passendstem",
            L"passendsten",
            L"passendster",
            L"passendstes",
            L"passend",
            L"persönlich",
            L"plötzlich",
            L"plötzliche",
            L"plötzlichem",
            L"plötzlichen",
            L"plötzlicher",
            L"plötzliches",
            L"praktisch",
            L"praktische",
            L"praktischer",
            L"praktisches",
            L"prinzipiell",
            L"prinzipielle",
            L"prinzipiellem",
            L"prinzipiellen",
            L"prinzipieller",
            L"prinzipielles",
            L"problematisch",
            L"problematische",
            L"problematischem",
            L"problematischen",
            L"problematischer",
            L"problematisches",
            L"quasi",
            L"real",
            L"reale",
            L"realem",
            L"realen",
            L"realer",
            L"reales",
            L"realisierbar",
            L"realisierbare",
            L"realisierbarem",
            L"realisierbaren",
            L"realisierbarer",
            L"realisierbares",
            L"recht",
            L"reichlich",
            L"reiflich",
            L"relativ",
            L"relative",
            L"relativem",
            L"relativen",
            L"relativer",
            L"relatives",
            L"relevant",
            L"relevante",
            L"relevantem",
            L"relevanten",
            L"relevanter",
            L"relevantes",
            L"relevantere",
            L"relevanterem",
            L"relevanteren",
            L"relevanterer",
            L"relevanteres",
            L"relevantes",
            L"relevanteste",
            L"relevantestem",
            L"relevantesten",
            L"relevantester",
            L"relevantestes",
            L"restlos",
            L"richtig",
            L"richtige",
            L"richtigem",
            L"richtigen",
            L"richtiger",
            L"richtiges",
            L"richtiggehend",
            L"riesig",
            L"riesige",
            L"riesigem",
            L"riesigen",
            L"riesiger",
            L"riesiges",
            L"riesigste",
            L"riesigstem",
            L"riesigsten",
            L"riesigster",
            L"riesigstes",
            L"rundheraus",
            L"rundum",
            L"samt",
            L"sämtliche",
            L"sämtlichem",
            L"sämtlichen",
            L"sämtlicher",
            L"sämtliches",
            L"sattsam",
            L"schätzungsweise",
            L"schlecht",
            L"schlechte",
            L"schlechtem",
            L"schlechten",
            L"schlechter",
            L"schlechtere",
            L"schlechterem",
            L"schlechteren",
            L"schlechteres",
            L"schlechtes",
            L"schlechteste",
            L"schlechtestem",
            L"schlechtesten",
            L"schlechtester",
            L"schlechtestes",
            L"schlicht",
            L"schlichtweg",
            L"schließlich",
            L"schlussendlich",
            L"schnell",
            L"schnelle",
            L"schnellem",
            L"schnellen",
            L"schneller",
            L"schnelles",
            L"schon",
            L"schön",
            L"schöne",
            L"schönem",
            L"schönen",
            L"schöner",
            L"schönes",
            L"schwach",
            L"schwache",
            L"schwachem",
            L"schwachen",
            L"schwacher",
            L"schwächer",
            L"schwächere",
            L"schwächerem",
            L"schwächeren",
            L"schwächerer",
            L"schwächeres",
            L"schwaches",
            L"schwächste",
            L"schwächstem",
            L"schwächsten",
            L"schwächster",
            L"schwächstes",
            L"schwerlich",
            L"schwierig",
            L"schwierige",
            L"schwierigem",
            L"schwierigen",
            L"schwieriger",
            L"schwieriger",
            L"schwierigere",
            L"schwierigerem",
            L"schwierigeren",
            L"schwierigeres",
            L"schwieriges",
            L"schwierigste",
            L"schwierigstem",
            L"schwierigsten",
            L"schwierigster",
            L"schwierigstes",
            L"sehr",
            L"sei",
            L"seien",
            L"selbe",
            L"selben",
            L"selber",
            L"selbes",
            L"selbst",
            L"selbstredend",
            L"selbstverständlich",
            L"selbstverständliche",
            L"selbstverständlichem",
            L"selbstverständlichen",
            L"selbstverständlicher",
            L"selbstverständliches",
            L"selten",
            L"seltene",
            L"seltenem",
            L"seltenen",
            L"seltener",
            L"seltenes",
            L"seltsamerweise",
            L"sicher",
            L"sicherlich",
            L"sinnlos",
            L"so",
            L"sodass",
            L"sofern",
            L"sogar",
            L"soll",
            L"solle",
            L"sollen",
            L"sollte",
            L"sollten",
            L"solltest",
            L"somit",
            L"sondern",
            L"sonst",
            L"sowie",
            L"sowieso",
            L"sozusagen",
            L"stellenweise",
            L"stellenweiser",
            L"stellenweises",
            L"stetig",
            L"stets",
            L"tatsächlich",
            L"tatsächlichem",
            L"tatsächlichen",
            L"tatsächlicher",
            L"tatsächliches",
            L"teils",
            L"teilweise",
            L"teilweisen",
            L"total",
            L"trotz",
            L"trotzdem",
            L"typisch",
            L"typische",
            L"typischem",
            L"typischen",
            L"typischer",
            L"typischerweise",
            L"typisches",
            L"überall",
            L"überaus",
            L"überdies",
            L"überhaupt",
            L"üblich",
            L"übliche",
            L"üblichem",
            L"üblichen",
            L"üblicher",
            L"übliches",
            L"übrigens",
            L"um",
            L"ums",
            L"umständehalber",
            L"unbedingt",
            L"ungefähr",
            L"ungefähre",
            L"ungefährem",
            L"ungefähren",
            L"ungefährer",
            L"ungefähres",
            L"ungemein",
            L"ungenau",
            L"ungenaue",
            L"ungenauem",
            L"ungenauen",
            L"ungenauer",
            L"ungenauere",
            L"ungenauerem",
            L"ungenaueren",
            L"ungenaueres",
            L"ungenaues",
            L"unnötig",
            L"unnötige",
            L"unnötigem",
            L"unnötigen",
            L"unnötiger",
            L"unnötiges",
            L"unnötigste",
            L"unnötigstem",
            L"unnötigsten",
            L"unnötigster",
            L"unnötigstes",
            L"uns",
            L"unser",
            L"unsere",
            L"unserem",
            L"unseren",
            L"unserer",
            L"unseres",
            L"unterschiedlich",
            L"unterschiedliche",
            L"unterschiedlichem",
            L"unterschiedlichen",
            L"unterschiedlicher",
            L"unterschiedliches",
            L"vergleichbar",
            L"vergleichbare",
            L"vergleichbarem",
            L"vergleichbaren",
            L"vergleichbarer",
            L"vergleichbares",
            L"vergleichsweise",
            L"vermutlich",
            L"vermutliche",
            L"vermutlichem",
            L"vermutlichen",
            L"vermutlicher",
            L"vermutliches",
            L"vernachlässigen",
            L"verschieden",
            L"verschiedene",
            L"verschiedenem",
            L"verschiedenen",
            L"verschiedener",
            L"verschiedenes",
            L"verschwindend",
            L"verständlich",
            L"versuchen",
            L"versucht",
            L"versuchte",
            L"versuchtem",
            L"versuchten",
            L"versuchter",
            L"versuchtes",
            L"verwenden",
            L"verwendet",
            L"verwendete",
            L"verwendetem",
            L"verwendeten",
            L"verwendeter",
            L"verwendetes",
            L"viel",
            L"viele",
            L"vielem",
            L"vielen",
            L"vieler",
            L"vieles",
            L"vielfach",
            L"vielfache",
            L"vielfachem",
            L"vielfachen",
            L"vielfacher",
            L"vielfaches",
            L"vielleicht",
            L"viertens",
            L"voll",
            L"volle",
            L"voller",
            L"volles",
            L"vollends",
            L"völlig",
            L"völlige",
            L"völligem",
            L"völligen",
            L"völliger",
            L"völliges",
            L"vollkommen",
            L"vollkommene",
            L"vollkommenem",
            L"vollkommenen",
            L"vollkommener",
            L"vollkommenes",
            L"vollständig",
            L"vollständige",
            L"vollständigem",
            L"vollständigen",
            L"vollständiger",
            L"vollständiges",
            L"vonnöten",
            L"vorerst",
            L"vorteil",
            L"vorteile",
            L"vorteilen",
            L"vorzufinden",
            L"vorzufindene",
            L"vorzufindenem",
            L"vorzufindenen",
            L"vorzufindener",
            L"vorzufindenes",
            L"während",
            L"währenddessen",
            L"wahrscheinlich",
            L"wahrscheinliche",
            L"wahrscheinlichem",
            L"wahrscheinlichen",
            L"wahrscheinlicher",
            L"wahrscheinliches",
            L"wäre",
            L"wären",
            L"wärest",
            L"weil",
            L"weit",
            L"weitem",
            L"weiter",
            L"weitere",
            L"weiterem",
            L"weiteren",
            L"weiterer",
            L"weiteres",
            L"weiterhin",
            L"weitgehend",
            L"weitgehende",
            L"weitgehendem",
            L"weitgehenden",
            L"weitgehender",
            L"weitgehendes",
            L"welche",
            L"welchem",
            L"welchen",
            L"welcher",
            L"welches",
            L"wenig",
            L"wenige",
            L"wenigem",
            L"wenigen",
            L"weniger",
            L"weniges",
            L"wenigsten",
            L"wenigstens",
            L"wenn",
            L"wenngleich",
            L"werde",
            L"werden",
            L"weshalb",
            L"wichtig",
            L"wichtige",
            L"wichtigem",
            L"wichtigen",
            L"wichtiger",
            L"wichtigere",
            L"wichtigerem",
            L"wichtigeren",
            L"wichtigerer",
            L"wichtigeres",
            L"wichtiges",
            L"wichtigste",
            L"wichtigstem",
            L"wichtigsten",
            L"wichtigster",
            L"wichtigstes",
            L"wieder",
            L"wiederum",
            L"wiewohl",
            L"will",
            L"wir",
            L"wird",
            L"wirklich",
            L"wirkliche",
            L"wirklichem",
            L"wirklichen",
            L"wirklicher",
            L"wirkliches",
            L"wobei",
            L"wodurch",
            L"wofür",
            L"wogegen",
            L"woher",
            L"wohin",
            L"wohingegen",
            L"wohl",
            L"wohlgemerkt",
            L"wohlweislich",
            L"wollen",
            L"wollt",
            L"wollte",
            L"wollten",
            L"wolltest",
            L"wolltet",
            L"womit",
            L"womöglich",
            L"woraufhin",
            L"woraus",
            L"worin",
            L"wurde",
            L"wurden",
            L"würde",
            L"würden",
            L"würdest",
            L"zahlreich",
            L"zahlreiche",
            L"zahlreichem",
            L"zahlreichen",
            L"zahlreicher",
            L"zahlreiches",
            L"zeige",
            L"zeigen",
            L"zeitweise",
            L"ziemlich",
            L"zudem",
            L"zufällig",
            L"zugegeben",
            L"zugegebenermaßen",
            L"zuletzt",
            L"zumeist",
            L"zusehends",
            L"zusehens",
            L"zuweilen",
            L"zwangsläufig",
            L"zwar",
            L"zweifellos",
            L"zweifelsfrei",
            L"zweifelsohne",
            L"zweitens",
            L"zusammenfassend",
            L"zusätzlich",
            L"zuvor",
        },
        {
            L"als ganzes",
            L"an sich",
            L"aufgabe ist",
            L"aufgabe war",
            L"aufgefasst werden",
            L"aufgefasst wird",
            L"aufs neue",
            L"bei weitem",
            L"befinden sich",
            L"befindet sich",
            L"bezogen auf",
            L"dargestellt ist",
            L"dargestellt war",
            L"dargestellt worden",
            L"das ganze",
            L"des öfteren",
            L"diese arbeit",
            L"dieser arbeit",
            L"diesem kapitel",
            L"diesem projekt",
            L"dort ist",
            L"dort war",
            L"ein beispiel",
            L"ein bisschen",
            L"ein teil",
            L"ein wenig",
            L"ergeben sich",
            L"ergibt sich",
            L"es kann",
            L"gab es",
            L"gar nicht",
            L"geschehen durch",
            L"geschehen über",
            L"geschieht durch",
            L"geschieht über",
            L"gibt es",
            L"gezeigt wurde",
            L"hier ist",
            L"hinzu kommt",
            L"hinzu kommen",
            L"im allgemeinen",
            L"im folgenden",
            L"im gegensatz",
            L"im prinzip",
            L"im vergleich",
            L"im wesentlichen",
            L"immer häufiger",
            L"immer mehr",
            L"immer weniger",
            L"in wirklichkeit",
            L"lassen sich",
            L"lässt sich",
            L"letzten schritt",
            L"letzten schritten",
            L"ließe sich",
            L"ließen sich",
            L"meines erachtens",
            L"mit ausnahme",
            L"nächsten schritt",
            L"nächsten schritten",
            L"nicht viel",
            L"ohne weiteres",
            L"ohne zweifel",
            L"sehen lassen",
            L"sehen lässt",
            L"von neuem",
            L"vor allem",
            L"ziel ist",
            L"ziel war",
            L"zu benutzen",
            L"zu erhöhen",
            L"zu erkennen",
            L"zu ermöglichen",
            L"zu finden",
            L"zu können",
            L"zu machen",
            L"zu maximieren",
            L"zu messen",
            L"zu minimieren",
            L"zu optimieren",
            L"zu rechnen",
            L"zu sagen",
            L"zu sehen",
            L"zu senken",
            L"zu verbessern",
            L"zu verhindern",
            L"zu zeigen",
            L"zum beispiel",
            L"zum teil",
            L"zweck ist",
            L"zweck liegt",
            L"zweck war",
        },
        {
            L"allem anschein nach",
            L"alles in allem",
            L"auf jeden fall",
            L"beim letzten mal",
            L"beim nächsten mal",
            L"dann und wann",
            L"das führt dazu",
            L"der vorteil in",
            L"ein beispiel für",
            L"es ergeben sich",
            L"es ergibt sich",
            L"für den fall",
            L"für sich genommen",
            L"gang und gäbe",
            L"ganz und gar",
            L"handelt es sich",
            L"handelte es sich",
            L"hat die aufgabe",
            L"hatte die aufgabe",
            L"hat das ziel",
            L"hatte das ziel",
            L"hier und da",
            L"in allen fällen",
            L"im grunde genommen",
            L"im letzten schritt",
            L"im nächsten schritt",
            L"in dem fall",
            L"in dem zusammenhang",
            L"in der arbeit",
            L"in der folgenden",
            L"in den folgenden",
            L"in der praxis",
            L"in der tat",
            L"in der realität",
            L"in der regel",
            L"in diesem fall",
            L"in diesen fällen",
            L"in diesem zusammenhang",
            L"in jedem fall",
            L"in unserem fall",
            L"in unserer arbeit",
            L"ist es aufgabe",
            L"ist es möglich",
            L"ist es ziel",
            L"mehr oder weniger",
            L"meiner meinung nach",
            L"mit bezug auf",
            L"mit großer wahrscheinlichkeit",
            L"mit größter wahrscheinlichkeit",
            L"samt und sonders",
            L"sowohl als auch",
            L"und so weiter",
            L"unserer meinung nach",
            L"voll und ganz",
            L"war die aufgabe",
            L"waren die aufgaben",
            L"warum auch immer",
            L"weshalb auch immer",
            L"wieso auch immer",
            L"zu guter letzt",
            L"zur verwendung kam",
            L"zur verwendung kamen",
            L"zur verwendung kommen",
            L"zur verwendung kommt",
        }
    };

}

#endif
