name: Build Test

 
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build
        run: sudo make install
        
  build-mac:
    runs-on: macos-latest
    timeout-minutes: 6
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build
        run: sudo make install PREFIX=/usr/local/bin

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 6
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
                
      - name: Install make
        run: choco install make
        
      - name: Build program
        run: make install PREFIX=C:/
