name: Build Test

 
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build
        run: sudo make install
        
  build-mac:
    runs-on: macos-latest
    timeout-minutes: 6
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up GCC
        run: brew upgrade gcc
        
      - name: Build
        run: sudo make install

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 6
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up GCC
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
        
      - name: Install make
        run: choco install make
        
      - name: Build program
        run: sudo make install PREFIX=C:/
