name: Build And Test

 
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build
        run: sudo make install
      
        # Enforce tty while testing, see https://github.com/actions/runner/issues/241#issuecomment-842566950
      - name: Test
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: ./tests/tests.sh
        
  build-mac:
    runs-on: macos-latest
    timeout-minutes: 6
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build
        run: sudo make install PREFIX=/usr/local/bin

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 6
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
                
      - name: Install make
        run: choco install make
        
      - name: Build
        run: make install PREFIX=C:/

